# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Ask your Documents Anything

nav:
  - Home: index.md
  - Installation: installation.md
  - Commands: commands.md
  - Zotero: zotero.md

theme:
  name: material
  palette:
    primary: pink

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
